//
//  PostViewController.swift
//  VIPTest
//
//  Created by AnkurPipaliya on 12/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostProtocol: class {
    func showActivityIndicator()
    func hideActivityIndicator()
    func checkInternectConnectionAvailable() -> Bool
    func displayAlert(string:String)
    func displayNoNetworkAlert(complationNoNetwork:(()->())?)
    func successfullyGetPost(data:[PostModel]?)
    
}

class PostViewController: BaseViewController, PostProtocol {
    
    @IBOutlet weak var tblPost: UITableView!
    func successfullyGetPost(data: [PostModel]?) {
        guard let arr = data, !arr.isEmpty else {return}
        print( " total Values in post : \(arr.count)")
       // var arrnew = [PostModel]()
       
        self.arrPost = arr
        DispatchQueue.main.async {
            self.tblPost.reloadData()
        }
    }
    
    //var interactor : PostInteractorProtocol?
    var presenter : PostPresentationProtocol?
    var arrPost = [PostModel]()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = PostInteractor()
        let presenter = PostPresenter()
        
        //View Controller will communicate with only presenter
        viewController.presenter = presenter
        //viewController.interactor = interactor
        
        //Presenter will communicate with Interector and Viewcontroller
        presenter.viewController = viewController
        presenter.interactor = interactor
        
        //Interactor will communucate with only presenter.
        interactor.presenter = presenter
    }
    
    
    // MARK: UIView life cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        self.setUI()
        print("PostViewController running....")
        // presenter?.apiCallingCityList(idCity: idFromState)
        //presenter?.apiCallingForPost(model: PostModel)
        presenter?.apiCallingForPost(model: arrPost)
      //  tblPost.register(UITableViewCell.self, forCellReuseIdentifier: "postCell" )
        
        self.tblPost.dataSource = self
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.setLocalization()
    }
    
    //MARK: Set UI and Localization
    func setUI() {
        
    }
    
    func setLocalization() {
        
    }
    
    // MARK: PostProtocol Methods
    func showActivityIndicator() {
        self.showSpinner()
    }
    
    func hideActivityIndicator() {
        self.hideSpinner()
    }
    
    
    func checkInternectConnectionAvailable() -> Bool {
        if !self.isInternetAvailable() {
            return false
        }
        return true
    }
    
    func displayAlert(string:String) {
        self.showAlert(title: "", message: string)
    }
    
    func displayNoNetworkAlert(complationNoNetwork:(()->())? = nil) {
        let strTitle = complationNoNetwork != nil ? KeyMessages.kALERT_TRY_AGAIN : ""
        self.showNoNetworkAlert(strBtnTitle: strTitle) {
            complationNoNetwork?()
        }
    }
    
    @IBAction func btnBackAction(_ sender: UIButton) {
        self.popVC()
    }
    
    
    
}

extension PostViewController : UITableViewDataSource
{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return arrPost.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
    {
        let cell = tableView.dequeueReusableCell(withIdentifier: "PostCell", for: indexPath) as! PostCell
        
        let index = arrPost[indexPath.row]
        cell.lblId?.text =  "\(index.id)"
        cell.lblBody.text = index.body
        cell.lblTitle.text = index.title
        return cell
    }
}

extension PostViewController : UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        // navigate to detail view controller
        let detailVC = storyboard?.instantiateViewController(withIdentifier: "CommentViewController") as! CommentViewController
        detailVC.getId = arrPost[indexPath.row].id
        self.navigationController?.pushViewController(detailVC, animated: true)
    }
}
