//
//  PostPresenter.swift
//  VIPTest
//
//  Created by AnkurPipaliya on 12/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostPresentationProtocol {
    func checkValidation(dictData:[String:Any]) -> Bool
    //Response
    func apiResponseForPost(body:[PostModel], message:String)
    //Request
    func apiCallingForPost(model: [PostModel])

}

class PostPresenter: PostPresentationProtocol {
    
    weak var viewController: PostProtocol?
    var interactor: PostInteractorProtocol?
    
    func checkValidation(dictData:[String:Any]) -> Bool {
        
        return true
    }
    func apiCallingForPost(model: [PostModel]) {
        if !(viewController?.checkInternectConnectionAvailable() ?? false) {
            viewController?.displayNoNetworkAlert(complationNoNetwork: nil)
            return
        }
        self.viewController?.showActivityIndicator()
        self.interactor?.fetchPostsfromApi(param: model)
    }
    
    func apiResponseForPost(body: [PostModel], message: String) {
//        viewController?.successfullyLogin(msg: message, body: body)
        viewController?.successfullyGetPost(data: body)
        self.viewController?.hideActivityIndicator()
        

    }
}
