//
//  CommentPresenter.swift
//  VIPTest
//
//  Created by AnkurPipaliya on 13/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentPresentationProtocol {
    func checkValidation(dictData:[String:Any]) -> Bool
    //Response
    func apiResponseForcomment(body:[CommentModel])
    //Request
    func apiCallingForComment(_id: Int, model : [CommentModel])
}

class CommentPresenter: CommentPresentationProtocol {

    weak var viewController: CommentProtocol?
    var interactor: CommentInteractorProtocol?
    
    func checkValidation(dictData:[String:Any]) -> Bool {
        
        return true
    }
    func apiCallingForComment(_id: Int, model: [CommentModel]) {        if !(viewController?.checkInternectConnectionAvailable() ?? false) {
            viewController?.displayNoNetworkAlert(complationNoNetwork: nil)
            return
        }
        self.viewController?.showActivityIndicator()
        self.interactor?.fetchCommentfromApi(_id: _id, model: model)
    }
    func apiResponseForcomment(body: [CommentModel]) {
        viewController?.successfullyGetComment(data: body)
        self.viewController?.hideActivityIndicator()
    }
    
  
    
}
